name: Web Tests

on:
  push:
    paths:
      - "apps/web/**"
  pull_request:
    paths:
      - "apps/web/**"

permissions:
  contents: read

defaults:
  run:
    working-directory: apps/web

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint, typecheck & build

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@0f3960b642f0c67a58e2a3577e908c98e8b41d4c # v6.0.0
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint .

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
